# Generated by Django 4.2 on 2023-05-01 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_friend_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='friend',
            unique_together=set(),
        ),
    ]
