# Generated by Django 4.2 on 2023-05-06 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_maticoffeeuser_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maticoffeeuser',
            name='profile_img',
            field=models.ImageField(default='src/profile_images/default.png', upload_to='src/profile_images'),
        ),
    ]
