# Generated by Django 4.2 on 2023-05-09 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_maticoffeeuser_profile_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='maticoffeeuser',
            name='last_person_chat',
            field=models.IntegerField(null=True),
        ),
    ]
